
    drop table if exists :SCHEMA.minrank
;      
        CREATE UNLOGGED TABLE :SCHEMA.minRank AS (
            SELECT gene_source_id
              , MIN(rank) as min_rank
            FROM :SCHEMA.uniprotGenes  upg
            WHERE hit_length is not null
            GROUP BY gene_source_id
        )
      
    ;

    drop table if exists :SCHEMA.alphafoldhits;
      
        CREATE UNLOGGED TABLE :SCHEMA.alphaFoldHits AS (
          SELECT DISTINCT gene_source_id
            , last_value(primary_identifier) over (PARTITION BY gene_source_id ORDER BY hit_length ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS uniprot_id
          FROM (
            SELECT upg.*
            FROM :SCHEMA.uniprotGenes  upg
              , :SCHEMA.minRank
            WHERE upg.gene_source_id = minRank.gene_source_id
            AND upg.rank = minRank.min_rank
          ) t
        )
    ;

        CREATE TABLE :SCHEMA.AlphaFoldGenes  AS (
          SELECT afh.gene_source_id
            , af.uniprot_id
            , af.source_id as alphafold_id
            , af.alphafold_version
            , af.first_residue_index
            , af.last_residue_index
          FROM apidb.alphafold af
            , :SCHEMA.alphaFoldHits afh
          WHERE afh.uniprot_id = af.uniprot_id
        )
      
    ;

    drop table if exists :SCHEMA.uniprotgenes;
    drop table if exists :SCHEMA.minrank;
    drop table if exists :SCHEMA.alphafoldhits;

