    create table :SCHEMA.GeneOrthologGroup as        
        SELECT DISTINCT pa.gene_source_id AS gene_id,
               ogas.group_id
        FROM webready.proteinattributes pa,
             apidb.orthologgroupaasequence ogas
        WHERE pa.aa_sequence_id = ogas.aa_sequence_id;
    alter table :SCHEMA.GeneOrthologGroup
    ADD CONSTRAINT GeneOrthologGroup_pk PRIMARY KEY (gene_id, group_id);

