
      
        CREATE table GroupPhylogeneticProfile  as
        SELECT rep.orthomcl_name, pp.profile_string
        FROM apidb.PhylogeneticProfile pp,
             (SELECT orthomcl_name, max(source_id) as source_id
              FROM GeneAttributes
              GROUP BY orthomcl_name) rep
        WHERE rep.source_id = pp.source_id
      
    ;


      
        create index group_pp_ix 
          on GroupPhylogeneticProfile  (orthomcl_name)

      
    ;

