DO $$
    DECLARE org record:PLPGSQL_DELIM
    BEGIN
        FOR org IN (SELECT DISTINCT abbrev, taxon_id FROM apidb.organism)
        LOOP

          EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.MinRanks_%L', org_rec.abbrev):PLPGSQL_DELIM
		      

          EXECUTE format('CREATE UNLOGGED TABLE :SCHEMA.MinRank_%L  AS
            SELECT gene_source_id
              , MIN(rank) as min_rank
            FROM :SCHEMA.uniprotGenes  upg
            WHERE hit_length is not null
	    and upg.org_abbrev = org.abbrev
            GROUP BY gene_source_id', org.abbrev):PLPGSQL_DELIM

          EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.AlphaFoldHits_%L', org_rec.abbrev):PLPGSQL_DELIM
		      

          EXECUTE format('CREATE UNLOGGED TABLE :SCHEMA.AlphaFoldHits_%L  AS
          SELECT DISTINCT gene_source_id
            , last_value(primary_identifier) over (PARTITION BY gene_source_id ORDER BY hit_length ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS uniprot_id
          FROM (
            SELECT upg.*
            FROM :SCHEMA.uniprotGenes  upg
              , :SCHEMA.minRank_%L
            WHERE upg.gene_source_id = minRank.gene_source_id
            AND upg.rank = minRank.min_rank
	    and upg.org_abbrev = org.abbrev
          ) t', org.abbrev):PLPGSQL_DELIM

          EXECUTE format('
          INSERT INTO :SCHEMA.AlphaFoldGenes (gene_source_id, uniprot_id, alphafold_id, alphafold_version, first_residue_index
	    last_residue_index, hit_length, org_abbrev, project_id, modification_date)
          SELECT afh.gene_source_id
            , af.uniprot_id
            , af.source_id as alphafold_id
            , af.alphafold_version
            , af.first_residue_index
            , af.last_residue_index
	    , (af.last_residue_index - af.first_residue_index + 1) as hit_length
	    , org.abbrev
	    , :PROJECT_ID
	    , current_timestamp
          FROM apidb.alphafold af
            , :SCHEMA.alphaFoldHits_%L afh
          WHERE afh.uniprot_id = af.uniprot_id', org.abbrev):PLPGSQL_DELIM


      EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.MinRank_%L', org_rec.abbrev):PLPGSQL_DELIM
      EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.AlphaFoldHits_%L', org_rec.abbrev):PLPGSQL_DELIM

  END LOOP:PLPGSQL_DELIM
END $$;


