
/* ATTENTION: This script is run using a custom workflow step class */
/* This accommodates the required to retain an empty table on undo */

TRUNCATE TABLE :SCHEMA.RefSynOrthologousGenes_p;

DO $$
DECLARE
  orgrecord RECORD:PLPGSQL_DELIM
  partition_name TEXT:PLPGSQL_DELIM
BEGIN
  FOR orgrecord IN
        SELECT org_abbrev, sanitized_org_abbrev, ref_strain_abbrev as ref_org_abbrev
  FROM :SCHEMA.organismabbreviation_p oa, apidb.organism o
  WHERE oa.org_abbrev = o.abbrev
  LOOP
    INSERT INTO :SCHEMA.RefSynOrthologousGenes_p (source_id, ref_source_id, org_abbrev, project_id, modification_date)
      WITH syn_pairs AS (
      SELECT DISTINCT ga.source_id, sg.syn_na_feature_id as ref_na_feature_id
      FROM :SCHEMA.SyntenicGene_p sg, :SCHEMA.GeneAttributes_p ga
      WHERE sg.na_sequence_id = ga.na_sequence_id
        AND ga.org_abbrev = orgrecord.org_abbrev
        and sg.syn_organism_abbrev = orgrecord.ref_org_abbrev
        AND sg.end_max >= ga.start_min
        AND sg.start_min <= ga.end_max
    ),
           ortholog_pairs AS (SELECT gog.gene_id as source_id, ga_ref.na_feature_id as ref_na_feature_id, gog_ref.gene_id as ref_source_id
      FROM :SCHEMA.GeneOrthologGroup gog
      JOIN :SCHEMA.GeneOrthologGroup gog_ref ON gog.group_id = gog_ref.group_id
      JOIN :SCHEMA.GeneAttributes_p ga_ref on gog_ref.gene_id = ga_ref.source_id
      WHERE gog.org_abbrev =  orgrecord.org_abbrev
        AND gog_ref.org_abbrev = orgrecord.ref_org_abbrev
        and ga_ref.org_abbrev = orgrecord.ref_org_abbrev
                )
     SELECT ortholog_pairs.source_id, ortholog_pairs.ref_source_id, orgrecord.org_abbrev, ':PROJECT_ID', current_timestamp
     FROM ortholog_pairs
     INNER JOIN syn_pairs ON ortholog_pairs.source_id = syn_pairs.source_id AND ortholog_pairs.ref_na_feature_id = syn_pairs.ref_na_feature_id
     UNION
     SELECT ga.source_id, ga.source_id as ref_source_id, ga.org_abbrev, ga.project_id, current_timestamp
     FROM :SCHEMA.geneattributes_p  ga
     WHERE ga.org_abbrev = orgrecord.org_abbrev
     AND ga.org_abbrev = orgrecord.ref_org_abbrev:PLPGSQL_DELIM
  END LOOP:PLPGSQL_DELIM
END $$;

