CREATE INDEX GOG_gene ON :SCHEMA.GeneOrthologGroup (gene_id);
CREATE INDEX GOG_abbrev ON :SCHEMA.GeneOrthologGroup (org_abbrev);
CREATE INDEX GOG_group ON :SCHEMA.GeneOrthologGroup (group_id);
CREATE UNIQUE INDEX GOG_genegroup ON :SCHEMA.GeneOrthologGroup  (gene_id, group_id);

CREATE UNIQUE INDEX transcriptog_abbrevsource ON :SCHEMA.TranscriptOrthologGroup  (org_abbrev, source_id);
CREATE INDEX transcriptog_source ON :SCHEMA.TranscriptOrthologGroup (source_id);
CREATE INDEX transcriptog_group ON :SCHEMA.TranscriptOrthologGroup (group_id);
CREATE INDEX transcriptog_gene ON :SCHEMA.TranscriptOrthologGroup (gene_id);
CREATE INDEX transcriptog_abbrev ON :SCHEMA.TranscriptOrthologGroup (org_abbrev);