Truncate table :SCHEMA.GeneOrthologGroup;
Truncate table :SCHEMA.TranscriptOrthologGroup;

DO $$
    DECLARE org_record record:PLPGSQL_DELIM
    BEGIN
        FOR org IN (SELECT DISTINCT abbrev, taxon_id FROM apidb.organism)
        LOOP

          EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.ProteinAttrsEcDerived_%L', org_rec.abbrev):PLPGSQL_DELIM
		      

          EXECUTE format('CREATE UNLOGGED TABLE :SCHEMA.ProteinAttrsEcDerived_%L  AS
                          SELECT aa_sequence_id, SUBSTR(string_agg(ec_number, ';' order by ec_number),1, 300) AS ec_numbers_derived
                          FROM (
			    SELECT DISTINCT asec.aa_sequence_id,
                            ec.ec_number || ' (' || ec.description || ')' AS ec_number
                            FROM dots.AaSequenceEnzymeClass asec, sres.EnzymeClass ec, dots.aasequence seq
                            WHERE ec.enzyme_class_id = asec.enzyme_class_id
                            AND seq.aa_sequence_id = asec.aa_sequence_id
                            AND asec.evidence_code = 'OrthoMCLDerived'
			    AND seq.taxon_id = org_record.taxon_id
                           ) t
                         GROUP BY aa_sequence_id',
			 org_record.abbrev):PLPGSQL_DELIM

         EXECUTE format('CREATE INDEX PAED_aaSequenceId_%L ON :SCHEMA.ProteinAttrsEcDerived_%L (aa_sequence_id)',
	                org_record.abbrev, org_record.abbrev):PLPGSQL_DELIM

         EXECUTE format('
	 INSERT INTO :SCHEMA.GeneOrthologGroup (gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, gene_paralog_number, gene_ortholog_number, modification_date)
         SELECT pa.gene_source_id AS gene_id,
           ogas.group_id,
           pa.project_id,
           pa.org_abbrev,
           ecDerived.ec_numbers_derived,
           0 as gene_paralog_number, 
           0 as gene_ortholog_number,
           current_timestamp as modification_date
         FROM :SCHEMA.proteinattributes pa
         JOIN apidb.orthologgroupaasequence ogas
           ON pa.aa_sequence_id = ogas.aa_sequence_id
         LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_%L ecDerived 
           ON ogas.aa_sequence_id = ecDerived.aa_sequence_id
	 WHERE pa.org_abbrev = org_record.abbrev
	 ', org_record.abbrev):PLPGSQL_DELIM

         EXECUTE format('
         INSERT INTO :SCHEMA.TranscriptOrthologGroup (source_id, gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, gene_paralog_number, gene_ortholog_number, modification_date)
SELECT ta.source_id AS source_id,
           ta.gene_source_id as gene_id,
           ogas.group_id,
           ta.project_id,
           ta.org_abbrev,
           ecDerived.ec_numbers_derived,
           0 as gene_paralog_number, 
           0 as gene_ortholog_number,
           current_timestamp as modification_date
       FROM :SCHEMA.transcriptattributes ta
       JOIN apidb.orthologgroupaasequence ogas
           ON ta.aa_sequence_id = ogas.aa_sequence_id
       LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_%L ecDerived 
           ON ogas.aa_sequence_id = ecDerived.aa_sequence_id
       WHERE ta.org_abbrev = org_record.abbrev
       ', org_record.abbrev):PLPGSQL_DELIM

      -- temp indexes
      EXECUTE format('CREATE INDEX GOG_neededForUpdate_%L ON :SCHEMA.GeneOrthologGroup (org_abbrev, group_id, gene_id)', org_record.abbrev ):PLPGSQL
      EXECUTE format('CREATE INDEX transcriptog_neededForUpdate_%L ON :SCHEMA.TranscriptOrthologGroup  (org_abbrev, source_id, group_id)', org_record.abbrev ):PLPGSQL

       UPDATE :SCHEMA.GeneOrthologGroup gog
       SET gene_paralog_number = (
           SELECT count(distinct gene_id)
           FROM :SCHEMA.GeneOrthologGroup g1
           JOIN :SCHEMA.GeneAttributes ga
               ON ga.gene_source_id = g1.gene_id
           WHERE gog.org_abbrev = org_record.abbrev
	   AND ga.org_abbrev = org_record.abbrev
	   AND g1.org_abbrev = org_record.abbrev
           AND gog.group_id = g1.group_id
           AND gog.gene_id != g1.gene_id
           AND ga.gene_type = 'protein coding' or ga.gene_type = 'protein coding gene')
       ):PLPGSQL_DELIM

       UPDATE :SCHEMA.TranscriptOrthologGroup tog
       SET gene_paralog_number = (
           SELECT count(distinct gene_source_id)
           FROM :SCHEMA.TranscriptOrthologGroup t1
           JOIN :SCHEMA.TranscriptAttributes ta
               ON ta.gene_source_id = t1.gene_id
           WHERE tog.org_abbrev = org_record.abbrev
           AND ta.org_abbrev = org_record.abbrev
           AND t1.org_abbrev = org_record.abbrev
           AND tog.group_id = t1.group_id
           AND tog.gene_id != t1.gene_id
           AND ta.gene_type = 'protein coding' or ta.gene_type = 'protein coding gene')
       ):PLPGSQL_DELIM
       
    EXECUTE format('DROP TABLE IF EXISTS :SCHEMA.ProteinAttrsEcDerived_%L', org_rec.abbrev):PLPGSQL_DELIM

    -- drop temp indexes
    EXECUTE format('DROP INDEX :SCHEMA.GOG_neededForUpdate_%L', org_record.abbrev ):PLPGSQL
    EXECUTE format('DROP INDEX :SCHEMA.transcriptog_neededForUpdate_%L', org_record.abbrev ):PLPGSQL

  END LOOP:PLPGSQL_DELIM
END $$;

-- temp indexes
CREATE INDEX GOG_neededForUpdate ON :SCHEMA.GeneOrthologGroup (org_abbrev, group_id, gene_id);
CREATE INDEX transcriptog_neededForUpdate ON :SCHEMA.TranscriptOrthologGroup  (org_abbrev, source_id, group_id);

-- do out-of-organism updates outside the LOOP

 UPDATE :SCHEMA.TranscriptOrthologGroup tog
       SET gene_ortholog_number = (
           SELECT count(distinct gene_source_id)
           FROM :SCHEMA.TranscriptOrthologGroup t1
           JOIN :SCHEMA.TranscriptAttributes ta
               ON ta.gene_source_id = t1.gene_id
           WHERE tog.org_abbrev != t1.org_abbrev
           AND tog.group_id = t1.group_id
           AND tog.gene_id != t1.gene_id
           AND ta.gene_type = 'protein coding' or ta.gene_type = 'protein coding gene';

 UPDATE :SCHEMA.TranscriptOrthologGroup tog
       SET gene_ortholog_number = (
           SELECT count(distinct gene_source_id)
           FROM :SCHEMA.TranscriptOrthologGroup t1
           JOIN :SCHEMA.TranscriptAttributes ta
               ON ta.gene_source_id = t1.gene_id
           WHERE tog.org_abbrev != t1.org_abbrev
           AND tog.group_id = t1.group_id
           AND tog.gene_id != t1.gene_id
           AND ta.gene_type = 'protein coding' or ta.gene_type = 'protein coding gene'
       );

-- don't leave these hanging around .. if needed, should add to the file which makes the "official" indexs.
drop index :SCHEMA.transcriptog_neededForUpdate;
drop index :SCHEMA.GOG_neededForUpdate;
