Truncate table :SCHEMA.GeneOrthologGroup;
Truncate table :SCHEMA.TranscriptOrthologGroup;
DROP TABLE IF EXISTS :SCHEMA.ProteinAttrsEcDerived_tmp;

CREATE UNLOGGED TABLE :SCHEMA.ProteinAttrsEcDerived_tmp  AS
SELECT aa_sequence_id, SUBSTR(string_agg(ec_number, ';' order by ec_number),1, 300) AS ec_numbers_derived
FROM (SELECT DISTINCT asec.aa_sequence_id,
ec.ec_number || ' (' || ec.description || ')' AS ec_number
FROM dots.AaSequenceEnzymeClass asec, sres.EnzymeClass ec, dots.aasequence seq
WHERE ec.enzyme_class_id = asec.enzyme_class_id
AND seq.aa_sequence_id = asec.aa_sequence_id
AND asec.evidence_code = 'OrthoMCLDerived'
) t
GROUP BY aa_sequence_id;

insert into :SCHEMA.GeneOrthologGroup (gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, modification_date)
SELECT ga.gene_source_id AS gene_id,
    ogas.group_id,
    ga.project_id,
    ga.org_abbrev,
    ecDerived.ec_numbers_derived,
    current_timestamp as modification_date
FROM :SCHEMA.proteinattributes ga
JOIN apidb.orthologgroupaasequence ogas
    ON ga.aa_sequence_id = ogas.aa_sequence_id
LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_tmp ecDerived 
    ON ogas.aa_sequence_id = ecDerived.aa_sequence_id;

insert into :SCHEMA.TranscriptOrthologGroup (source_id, gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, modification_date)
SELECT ta.source_id AS source_id,
       ta.gene_source_id as gene_id,
       ogas.group_id,
       ta.project_id,
       ta.org_abbrev,
       ecDerived.ec_numbers_derived,
       current_timestamp as modification_date
FROM :SCHEMA.transcriptattributes ta
JOIN apidb.orthologgroupaasequence ogas
    ON ta.aa_sequence_id = ogas.aa_sequence_id
LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_tmp ecDerived 
    ON ogas.aa_sequence_id = ecDerived.aa_sequence_id;

drop table :SCHEMA.ProteinAttrsEcDerived_tmp;