drop table :SCHEMA.GeneOrthologGroup CASCADE;
drop table :SCHEMA.TranscriptOrthologGroup CASCADE;
DROP TABLE IF EXISTS :SCHEMA.ProteinAttrsEcDerived_tmp;


CREATE UNLOGGED TABLE :SCHEMA.GeneOrthologGroup (
    gene_id   VARCHAR(80),
    group_id   VARCHAR(16),
    project_id  varchar(20),
    org_abbrev  varchar(30),
    ec_numbers_derived varchar(400),
    gene_paralog_number numeric(10),
    gene_ortholog_number numeric(10),
    modification_date   timestamp
);

-- temp index
CREATE INDEX GOG_neededForUpdate ON :SCHEMA.GeneOrthologGroup (org_abbrev, group_id, gene_id);

CREATE UNLOGGED TABLE :SCHEMA.TranscriptOrthologGroup (
    source_id   VARCHAR(80),
    gene_id   VARCHAR(80),
    group_id   VARCHAR(16),
    project_id  varchar(20),
    org_abbrev  varchar(30),
    ec_numbers_derived varchar(400),
    gene_paralog_number numeric(10),
    gene_ortholog_number numeric(10),
    modification_date   timestamp
);

-- temp index
CREATE INDEX transcriptog_neededForUpdate ON :SCHEMA.TranscriptOrthologGroup  (org_abbrev, source_id, group_id);

CREATE UNLOGGED TABLE :SCHEMA.ProteinAttrsEcDerived_tmp  AS
SELECT aa_sequence_id, SUBSTR(string_agg(ec_number, ';' order by ec_number),1, 300) AS ec_numbers_derived
FROM (SELECT DISTINCT asec.aa_sequence_id,
ec.ec_number || ' (' || ec.description || ')' AS ec_number
FROM dots.AaSequenceEnzymeClass asec, sres.EnzymeClass ec, dots.aasequence seq
WHERE ec.enzyme_class_id = asec.enzyme_class_id
AND seq.aa_sequence_id = asec.aa_sequence_id
AND asec.evidence_code = 'OrthoMCLDerived'
) t
GROUP BY aa_sequence_id;

CREATE INDEX PAED_aaSequenceId ON :SCHEMA.ProteinAttrsEcDerived_tmp (aa_sequence_id);

insert into :SCHEMA.GeneOrthologGroup (gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, gene_paralog_number, gene_ortholog_number, modification_date)
SELECT DISTINCT pa.gene_source_id AS gene_id, -- NEED DISTICT HERE because we are getting gene level info from proteins
    ogas.group_id,
    pa.project_id,
    pa.org_abbrev,
    ecDerived.ec_numbers_derived,
    0 as gene_paralog_number, 
    0 as gene_ortholog_number,
    current_timestamp as modification_date
FROM :SCHEMA.proteinattributes pa
JOIN apidb.orthologgroupaasequence ogas
    ON pa.aa_sequence_id = ogas.aa_sequence_id
LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_tmp ecDerived 
    ON pa.aa_sequence_id = ecDerived.aa_sequence_id;

insert into :SCHEMA.TranscriptOrthologGroup (source_id, gene_id, group_id, project_id, org_abbrev, ec_numbers_derived, gene_paralog_number, gene_ortholog_number, modification_date)
SELECT ta.source_id AS source_id, -- There is exactly one protein per transcript so no distinct needed here
    ta.gene_source_id as gene_id,
    ogas.group_id,
    ta.project_id,
    ta.org_abbrev,
    ecDerived.ec_numbers_derived,
    0 as gene_paralog_number, 
    0 as gene_ortholog_number,
    current_timestamp as modification_date
FROM :SCHEMA.transcriptattributes ta
JOIN apidb.orthologgroupaasequence ogas
    ON ta.aa_sequence_id = ogas.aa_sequence_id
LEFT JOIN :SCHEMA.ProteinAttrsEcDerived_tmp ecDerived 
    ON ta.aa_sequence_id = ecDerived.aa_sequence_id;

UPDATE :SCHEMA.GeneOrthologGroup gog
SET gene_paralog_number = (
    SELECT count(distinct gene_id)
    FROM :SCHEMA.GeneOrthologGroup g1
    WHERE gog.org_abbrev = g1.org_abbrev
    AND gog.group_id = g1.group_id
    AND gog.gene_id != g1.gene_id
),
gene_ortholog_number = (
    SELECT count(distinct gene_id)
    FROM :SCHEMA.GeneOrthologGroup g1
    WHERE gog.org_abbrev != g1.org_abbrev
    AND gog.group_id = g1.group_id
    AND gog.gene_id != g1.gene_id
);

UPDATE :SCHEMA.TranscriptOrthologGroup tog
SET gene_paralog_number = (
  select MAX(gog.gene_paralog_number)
    FROM :SCHEMA.GeneOrthologGroup gog
    JOIN :SCHEMA.TranscriptAttributes ta
      ON ta.source_id = tog.source_id
    WHERE tog.gene_id = gog.gene_id
    AND ta.so_term_name = 'protein_coding_gene'
),
gene_ortholog_number = (
  select MAX(gog.gene_ortholog_number)
    FROM :SCHEMA.GeneOrthologGroup gog
    JOIN :SCHEMA.TranscriptAttributes ta
      ON ta.source_id = tog.source_id
    WHERE tog.gene_id = gog.gene_id
    AND ta.so_term_name = 'protein_coding_gene'
)
;

drop table :SCHEMA.ProteinAttrsEcDerived_tmp;
--drop index PAED_aaSequenceId;

-- don't leave these hanging around .. if needed, should add to the file which makes the "official" indexs.
--drop index transcriptog_neededForUpdate;
--drop index GOG_neededForUpdate;
