
CREATE INDEX GOG_gene ON :SCHEMA.GeneOrthologGroup (gene_id, project_id, group_id);
CREATE INDEX GOG_genegroup ON :SCHEMA.GeneOrthologGroup  (gene_id, group_id);
CREATE INDEX GOG_group ON :SCHEMA.GeneOrthologGroup (group_id, gene_id, project_id);
CREATE INDEX GOG_group2 ON :SCHEMA.GeneOrthologGroup (org_abbrev, group_id, gene_id, project_id);


CREATE INDEX transcriptog_genepage ON :SCHEMA.TranscriptOrthologGroup  (source_id, project_id, gene_id, group_id);
CREATE INDEX transcriptog_grouptranscript ON :SCHEMA.TranscriptOrthologGroup (group_id, source_id);
CREATE INDEX transcriptog_groupgene ON :SCHEMA.TranscriptOrthologGroup (group_id, gene_id);
CREATE INDEX transcriptog_gene ON :SCHEMA.TranscriptOrthologGroup (gene_id);
