CREATE TABLE :SCHEMA.SyntenicGene_p (
 syntenic_gene_id            NUMERIC(10),
 na_sequence_id              NUMERIC(10),
 start_min                   NUMERIC,
 end_max                     NUMERIC,
 is_reversed                 NUMERIC(1),
 syn_na_feature_id          NUMERIC(10),
 syn_organism_abbrev         varchar(40),
 modification_date           TIMESTAMP
) partition by list (syn_organism_abbrev);

DO $$
DECLARE
  orgrecord RECORD:PLPGSQL_DELIM
  partition_name TEXT:PLPGSQL_DELIM
BEGIN
  FOR orgrecord IN SELECT org_abbrev, sanitized_org_abbrev from :SCHEMA.organismabbreviation_p LOOP
    partition_name := lower('syntenicgene_p_' || orgrecord.sanitized_org_abbrev):PLPGSQL_DELIM
    EXECUTE format('CREATE TABLE :SCHEMA.%I PARTITION OF :SCHEMA.SyntenicGene_p FOR VALUES IN (%L)', partition_name, orgrecord.org_abbrev):PLPGSQL_DELIM
  END LOOP:PLPGSQL_DELIM
END $$;

INSERT INTO :SCHEMA.SyntenicGene_p
select syntenic_gene_id, na_sequence_id, start_min, end_max,
       is_reversed, syn_na_feature_id, syn_organism_abbrev,  current_timestamp AS modification_date
from apidb.syntenicgene;
