* ApiCommonModel

Extends [[https://github.com/VEuPathDB/EbrModelCommon][EbrModelCommon]].

It includes xml files with basic data types definitions, and their structured searches, for genomic sites.
Api stands for 'Apicomplexan'. These are the first organisms included in our websites when they were first time publicly 
released as ApiDB BRC (Bioinformatics Resource Center), back in 2002.

** Dependencies

   + yarn / npm / ant
   + WEBAPP_PROP_FILE file (file with one property for the webapp target directory)
      webappTargetDir=BLAH
   + environment variables for GUS_HOME and PROJECT_HOME
   + Internal Dependencies
     + WDK, CBIL, ReFlow, EbrcModelCommon

** Installation instructions.

   + bld ApiCommonModel
   + changes to wdk model xml files requires reload of tomcat instance

** Operating instructions.

   + Installation is successful if you can run "wdkXml -model $MODEL_NAME" without error

** Manifest

   + Model/bin :: scripts referenced in tuning manager config and other tuning scripts (portallinker);  scripts for creating jbrowse configuration
   + Model/lib/dst :: dataset template files
   + Model/lib/jbrowse :: jbrowse configuration; common and organism specific tracks
   + Model/lib/perl :: utils for datasets and jbrowse
   + Model/lib/wdk :: xml files which define wdk records, searches, params.
   + Model/lib/xml :: tuning manager configuration, jbrowse queries, global dataset presenter xml
   + Model/src/main/java/org/apidb/apicommon/model/datasetInjector :: java code per data class for managing template injection
   + Model/src/main/java/org/apidb/apicommon/model/report :: reporters referenced in wdk xml
   + Model/src/main/java/org/apidb/apicommon/model/userdataset :: Type Handlers for User Datasets

