        CREATE TABLE :SCHEMA.CompoundId  AS
        SELECT source_id AS id, source_id AS compound, 'same ID' AS type, '' as source
        FROM :SCHEMA.CompoundAttributes
        UNION
        SELECT p.source_id AS id, ca.source_id AS compound, 'child ID' AS type, '' as source
        FROM :SCHEMA.CompoundAttributes ca, CompoundProperties p
        WHERE ca.id = p.parent_id
        UNION
        SELECT da.accession_number AS id,  p.source_id AS compound, 'KEGG'  AS type, '' as source
        FROM chebi.database_accession da, :SCHEMA.CompoundAttributes p
        WHERE da.type='KEGG COMPOUND accession'
        AND  da.compound_id = p.id
        UNION
        SELECT  distinct da.accession_number AS id,  p.chebi_accession AS compound, 'KEGG'  as type, '' as source
        FROM chebi.database_accession da, chebi.compounds c, chebi.compounds p
        WHERE NOT p.status in ('D', 'F') AND da.type='KEGG COMPOUND accession'
        AND da.compound_id = c.id AND c.parent_id=p.id
        UNION
        SELECT n.name as id, ca.source_id as compound, 'name' as type, n.source
        FROM :SCHEMA.CompoundAttributes ca, chebi.names n
        WHERE ca.id = n.compound_id
        AND n.type = 'NAME'
        UNION
        SELECT n.name as id, ca.source_id as compound, 'synonym' as type, n.source
        FROM :SCHEMA.CompoundAttributes ca, chebi.names n
        WHERE ca.id = n.compound_id
        AND n.type = 'SYNONYM'     
    ;
      
        CREATE INDEX :SCHEMA.CompoundId_idx  ON :SCHEMA.CompoundId  (id, compound)
    ;

