
      
CREATE TABLE GroupDomainAttribute  AS
(
SELECT og.group_id AS group_name, ag.descriptions
FROM apidb.OrthologGroup og,
     (SELECT group_name,
             STRING_AGG(accession ||' (' || num_proteins|| ')', ', ')  AS descriptions
      FROM (SELECT group_name, accession, num_proteins, rnk
            FROM (SELECT group_name, accession, num_proteins,
	                 rank() OVER (PARTITION BY group_name ORDER BY num_proteins DESC) rnk
		  FROM (SELECT group_name, accession, count(distinct full_id) AS num_proteins
		        FROM DomainAssignment
			GROUP BY group_name,accession
		        )
		  )
	    WHERE rnk <= 3
	    )
      GROUP BY group_name
      ORDER BY 1
      ) ag
WHERE  og.group_id = ag.group_name
)
      
    ;


      
CREATE INDEX GroupDomainAttribute_idx  ON GroupDomainAttribute  (group_name)
      
    ;

