
      
        CREATE TABLE PathwayCompounds  AS
        SELECT
          pathway_id
          , reaction_id
          , ext_db_name
          , ext_db_version
          , compound_node_id
          , compound_source_id
          , c.chebi_accession
          , case when c.chebi_accession is not null then 'https://www.ebi.ac.uk/chebi/searchId.do?chebiId=' || c.chebi_accession else null end as chebi_url
          , type
        FROM (
          SELECT
            p.PATHWAY_ID
            , prx.PATHWAY_REACTION_ID as reaction_id
            , ed.NAME as ext_db_name
            , edr.version as ext_db_version
            , pn.pathway_node_id as compound_node_id
            , pn.DISPLAY_LABEL as compound_source_id
            , 'substrate' as type
            , pn.row_id
          FROM
            APIDB.PATHWAYREACTION prx
            , SRES.PATHWAY p
            , APIDB.PATHWAYREACTIONREL prr
            , SRES.PATHWAYNODE pn
            , SRES.PATHWAYRELATIONSHIP prel
            , SRES.ONTOLOGYTERM ot
            , SRES.EXTERNALDATABASE ed
            , SRES.EXTERNALDATABASERELEASE edr
          WHERE p.PATHWAY_ID = prr.PATHWAY_ID
            AND prx.PATHWAY_REACTION_ID = prr.PATHWAY_REACTION_ID
            AND prr.PATHWAY_RELATIONSHIP_ID = prel.PATHWAY_RELATIONSHIP_ID
            AND prel.NODE_ID = pn.PATHWAY_NODE_ID
            AND ot.NAME = 'molecular entity'
            AND ot.ONTOLOGY_TERM_ID = pn.PATHWAY_NODE_TYPE_ID
            AND p.EXTERNAL_DATABASE_RELEASE_ID = edr.EXTERNAL_DATABASE_RELEASE_ID
            AND edr.EXTERNAL_DATABASE_ID = ed.EXTERNAL_DATABASE_ID
        ) t LEFT OUTER JOIN CHEBI.COMPOUNDS c on t.row_id = c.ID
        UNION
        SELECT
          pathway_id
          , reaction_id
          , ext_db_name
          , ext_db_version
          , compound_node_id
          , compound_source_id
          , c.chebi_accession
          , case when c.chebi_accession is not null then 'https://www.ebi.ac.uk/chebi/searchId.do?chebiId=' || c.chebi_accession else null end as chebi_url
          , type
        FROM (
          SELECT
            p.PATHWAY_ID
            , prx.PATHWAY_REACTION_ID as reaction_id
            , ed.NAME as ext_db_name
            , edr.version as ext_db_version
            , pn.pathway_node_id as compound_node_id
            , pn.DISPLAY_LABEL as compound_source_id
            , 'product' as type
            , pn.row_id
          FROM
            APIDB.PATHWAYREACTION prx
            , SRES.PATHWAY p
            , APIDB.PATHWAYREACTIONREL prr
            , SRES.PATHWAYNODE pn
            , SRES.PATHWAYRELATIONSHIP prel
            , SRES.ONTOLOGYTERM ot
            , SRES.EXTERNALDATABASE ed
            , SRES.EXTERNALDATABASERELEASE edr
          WHERE p.PATHWAY_ID = prr.PATHWAY_ID
            AND prx.PATHWAY_REACTION_ID = prr.PATHWAY_REACTION_ID
            AND prr.PATHWAY_RELATIONSHIP_ID = prel.PATHWAY_RELATIONSHIP_ID
            AND prel.ASSOCIATED_NODE_ID = pn.PATHWAY_NODE_ID
            AND ot.NAME = 'molecular entity'
            AND ot.ONTOLOGY_TERM_ID = pn.PATHWAY_NODE_TYPE_ID
            AND p.EXTERNAL_DATABASE_RELEASE_ID = edr.EXTERNAL_DATABASE_RELEASE_ID
            AND edr.EXTERNAL_DATABASE_ID = ed.EXTERNAL_DATABASE_ID
        ) t2 LEFT OUTER JOIN CHEBI.COMPOUNDS c on t2.row_id = c.ID
      
    ;


      
        create index PthCmpd_id_ix 
        on PathwayCompounds (pathway_id, reaction_id, ext_db_name)

      
    ;

