DROP TABLE IF EXISTS :SCHEMA.:CLEAN_ORG_ABBREVAlphaFoldGenesTmp;


/* ATTENTION: This table is empty. We will populate it in the comparative graph
   We are creating it here so that it is partitioned and exists early in the release cycle to avoid site failure */

create table :SCHEMA.:CLEAN_ORG_ABBREVAlphaFoldGenesTmp (
    gene_source_id   VARCHAR(80),
    uniprot_id   VARCHAR(80),
    alphafold_id   VARCHAR(80),
    alphafold_version   VARCHAR(80),
    project_id  varchar(20),
    first_residue_index integer,
    last_residue_index integer,
    hit_length integer,
    org_abbrev  varchar(30),
    modification_date   timestamp	
);


:CREATE_AND_POPULATE
SELECT * FROM :SCHEMA.:CLEAN_ORG_ABBREVAlphaFoldGenesTmp;
:DECLARE_PARTITION;

DROP TABLE :SCHEMA.:CLEAN_ORG_ABBREVAlphaFoldGenesTmp;
