:CREATE_AND_POPULATE
     select db.aa_feature_id,
            db.db_ref_id,
            ':PROJECT_ID' as project_id,
	    ':ORG_ABBREV' as org_abbrev,
	    CURRENT_TIMESTAMP as modification_date 
     from dots.dbrefaafeature db, dots.aafeature aa, webready.proteinattributes pa
     where db.aa_feature_id = aa.aa_feature_id
      and aa.aa_sequence_id = pa.aa_sequence_id
      and pa.org_abbrev = ':ORG_ABBREV';

:DECLARE_PARTITION;
