:CREATE_AND_POPULATE
        SELECT ':PROJECT_ID' as project_id, ':ORG_ABBREV' as org_abbrev, current_timestamp as modification_date,
        gene_source_id, haplotype_block_name as hapblock_id, sequence_id,
               start_min, end_max, start_max, end_min,
               max(score) as lod_score, organism
        FROM (SELECT ga.gene_source_id, ga.project_id, gls.haplotype_block_name,
                     ens.source_id as sequence_id, nl.start_min, nl.end_max, nl.start_max, nl.end_min,
                     gls.lod_score_mant * power(10::double precision, gls.lod_score_exp) as score,
                     replace (ga.organism, ' ', '+') as organism
              FROM dots.ChromosomeElementFeature cef, apidb.NAFeatureHaploblock gls,
                   dots.ExternalNaSequence ens, dots.NaLocation nl, :SCHEMA.TranscriptAttributes_p ga
              WHERE gls.na_feature_id = ga.gene_na_feature_id
                AND cef.name = gls.haplotype_block_name
                AND nl.na_feature_id = cef.na_feature_id
                AND cef.na_sequence_id = ens.na_sequence_id
                AND ga.org_abbrev = ':ORG_ABBREV'
                AND (gls.lod_score_mant * power(10::double precision, gls.lod_score_exp)) >= 1.5
        ) t
        GROUP BY gene_source_id, project_id, sequence_id, haplotype_block_name,
                 start_min, end_max, start_max, end_min, organism;
      
    
:DECLARE_PARTITION;

