:CREATE_AND_POPULATE
   SELECT feature_type, feature_source_id, sequence_source_id, fl.na_sequence_id, na_feature_id,
          start_min, end_max, is_reversed, parent_id, fl.sequence_ontology_id, is_top_level, fl.external_database_release_id,
          ':ORG_ABBREV' as org_abbrev, current_timestamp as modification_date
   FROM apidb.featurelocation fl, dots.nasequence s
   WHERE fl.na_sequence_id = s.na_sequence_id
     AND s.taxon_id = :TAXON_ID
    
:DECLARE_PARTITION;

