CREATE INDEX featloc_ix1  ON :SCHEMA.FeatureLocation (org_abbrev, na_sequence_id, start_min, end_max, is_reversed, sequence_ontology_id, na_feature_id, feature_type, parent_id);
CREATE INDEX featloc_ix2  ON :SCHEMA.FeatureLocation (org_abbrev, na_feature_id, na_sequence_id, start_min, end_max, is_reversed, sequence_ontology_id, feature_type, parent_id);
CREATE INDEX featloc_ix3  ON :SCHEMA.FeatureLocation (org_abbrev, na_sequence_id, feature_type, start_min, end_max, is_reversed, sequence_ontology_id, na_feature_id, parent_id);
CREATE INDEX featloc_ix4  ON :SCHEMA.FeatureLocation (org_abbrev, na_sequence_id, feature_type, end_max, start_min, is_reversed, sequence_ontology_id, na_feature_id, parent_id);
CREATE INDEX featloc_revix3  ON :SCHEMA.FeatureLocation (org_abbrev, parent_id);
CREATE INDEX featloc_revix4  ON :SCHEMA.FeatureLocation (org_abbrev, sequence_ontology_id);
CREATE INDEX featloc_revix5  ON :SCHEMA.FeatureLocation (org_abbrev, external_database_release_id);
