DROP TABLE if exists :SCHEMA.:CLEAN_ORG_ABBREVGeneOrthologGroupTmp;
/*

ATTENTION: This table is empty. We will populate it in the comparative graph
We are creating them it so that they it is partitioned.
*/

CREATE UNLOGGED TABLE :SCHEMA.:CLEAN_ORG_ABBREVGeneOrthologGroupTmp (
    gene_id   VARCHAR(80),
    group_id   VARCHAR(16),
    project_id  varchar(20),
    org_abbrev  varchar(30),
    ec_numbers_derived varchar(400),
    gene_paralog_number numeric(10),
    gene_ortholog_number numeric(10),
    modification_date   timestamp
);

:CREATE_AND_POPULATE
SELECT ogt.* from :SCHEMA.:CLEAN_ORG_ABBREVGeneOrthologGroupTmp ogt;
:DECLARE_PARTITION;


DROP TABLE :SCHEMA.:CLEAN_ORG_ABBREVGeneOrthologGroupTmp;
