:CREATE_AND_POPULATE
            SELECT DISTINCT ':PROJECT_ID' as project_id
            , ':ORG_ABBREV' as org_abbrev
            , current_timestamp as modification_date
            , ta.source_id
            , ta.gene_source_id
            , REGEXP_REPLACE(pan.name, '_[A-Za-z0-9]+ (.+)$', '') AS strain
            , gcn.haploid_number AS raw_estimate
            , gcn.ref_copy_number AS ref_cn
            , CASE WHEN (gcn.haploid_number < 0.01) THEN 0
                WHEN (0.01 < gcn.haploid_number AND gcn.haploid_number < 1.85) THEN 1
                ELSE round(gcn.haploid_number) END AS haploid_number
            , ta.chromosome
            , ta.na_sequence_id
            , io.input_pan_id
            , io.output_pan_id
            FROM apidb.genecopynumber gcn
            , study.protocolappnode pan
            , :SCHEMA.TranscriptAttributes ta
            , :SCHEMA.PANIo io
            WHERE gcn.protocol_app_node_id = pan.protocol_app_node_id
            AND gcn.na_feature_id = ta.gene_na_feature_id
            AND gcn.protocol_app_node_id = io.output_pan_id
            AND (ta.gene_type = 'protein coding' or ta.gene_type = 'protein coding gene')
            AND ta.org_abbrev = ':ORG_ABBREV'
            AND io.org_abbrev = ':ORG_ABBREV';
        
    
:DECLARE_PARTITION;

