DROP TABLE if exists :SCHEMA.:REF_ORG_ABBREVGeneOrthologGroupTmp;
/*

ATTENTION: This table is empty. We will populate it in the comparative graph
We are creating them it so that they it is partitioned.
*/

CREATE UNLOGGED TABLE :SCHEMA.:REF_ORG_ABBREVGeneOrthologGroupTmp (
    gene_id   VARCHAR(80),
    group_id   VARCHAR(16),
    project_id  varchar(20),
    org_abbrev  varchar(20),
    modification_date   timestamp
);

:CREATE_AND_POPULATE
SELECT ogt.* from :SCHEMA.:REF_ORG_ABBREVGeneOrthologGroupTmp ogt
:DECLARE_PARTITION;


DROP TABLE :SCHEMA.:REF_ORG_ABBREVGeneOrthologGroupTmp;
