        CREATE INDEX GeneId_gene_idx  ON :SCHEMA.GeneId  (gene, id)
    ;

        CREATE INDEX GeneId_id_idx  ON :SCHEMA.GeneId  (id, gene)
    ;

        CREATE INDEX GeneId_uniqid_idx  ON :SCHEMA.GeneId  (unique_mapping, id, gene)
    ;

        CREATE INDEX GeneId_lowid_idx  ON :SCHEMA.GeneId  (lower(id), gene)
    ;

        CREATE INDEX GeneId_uniqlowid_idx  ON :SCHEMA.GeneId  (unique_mapping, lower(id), gene)
    ;

