        CREATE INDEX GeneId_p_gene_idx  ON :SCHEMA.GeneId_p  (org_abbrev, gene, id)
    ;

        CREATE INDEX GeneId_p_id_idx  ON :SCHEMA.GeneId_p  (org_abbrev, id, gene)
    ;

        CREATE INDEX GeneId_p_uniqid_idx  ON :SCHEMA.GeneId_p  (org_abbrev, unique_mapping, id, gene)
    ;

        CREATE INDEX GeneId_p_lowid_idx  ON :SCHEMA.GeneId_p  (org_abbrev, lower(org_abbrev), id, gene)
    ;

        CREATE INDEX GeneId_p_uniqlowid_idx  ON :SCHEMA.GeneId_p  (org_abbrev, unique_mapping, lower(org_abbrev), id, gene)
    ;

