        CREATE INDEX GeneId_gene_idx  ON :SCHEMA.GeneId  (org_abbrev, gene, id)
    ;

        CREATE INDEX GeneId_id_idx  ON :SCHEMA.GeneId  (org_abbrev, id, gene)
    ;

        CREATE INDEX GeneId_uniqid_idx  ON :SCHEMA.GeneId  (org_abbrev, unique_mapping, id, gene)
    ;

        CREATE INDEX GeneId_lowid_idx  ON :SCHEMA.GeneId  (org_abbrev, lower(org_abbrev, id), gene)
    ;

        CREATE INDEX GeneId_uniqlowid_idx  ON :SCHEMA.GeneId  (org_abbrev, unique_mapping, lower(org_abbrev, id), gene)
    ;

