        create unique index pk_SeqAttr_  ON :SCHEMA.GenomicSeqAttributes_p  (org_abbrev, lower(source_id), project_id)
    ;

        create unique index SeqAttr_source_id  ON :SCHEMA.GenomicSeqAttributes_p  (org_abbrev, source_id)
    ;

        create unique index SeqAttr_naseqid  ON :SCHEMA.GenomicSeqAttributes_p  (org_abbrev, na_sequence_id)
    ;

        create unique index SeqAttr_taxsrc_id  ON :SCHEMA.GenomicSeqAttributes_p  (org_abbrev, taxon_id, source_id)
    ;
