:CREATE_AND_POPULATE
    SELECT DISTINCT ':PROJECT_ID' as project_id
        , ':ORG_ABBREV' as org_abbrev
        , gbg.sequence_source_id
        , gbg.start_location
        , gbg.end_location
        , gbg.algorithm
        , gbg.value
        , gbg.external_db_release_id
        , gbg.modification_date
    FROM apidb.genomebedgraph gbg,
         dots.nasequence nas,
         apidb.organism org
    WHERE gbg.sequence_source_id = nas.source_id
        AND nas.taxon_id = org.taxon_id
        AND org.abbrev = ':ORG_ABBREV'
;
:DECLARE_PARTITION;

