:CREATE_AND_POPULATE
        WITH org_tot AS (
          SELECT
            gs.organism
            , min(gij.total_unique) as min_annot_score
            , PERCENTILE_cont(0.005) within group (order by gij.total_unique asc) as perc005_annot_score
            , PERCENTILE_cont(0.01) within group (order by gij.total_unique asc) as perc01_annot_score
            , min(gij.percent_max) as min_annot_percent_max
            , PERCENTILE_cont(0.0001) within group (order by gij.percent_max asc) as perc0001_annot_percent_max
            , PERCENTILE_cont(0.0005) within group (order by gij.percent_max asc) as perc0005_annot_percent_max
            , floor(max(gij.segment_end - gij.segment_start) * 1.25) as max_intron_length
          FROM :SCHEMA.geneintronjunction gij
               , :SCHEMA.genomicseqattributes gs
          WHERE gs.na_sequence_id = gij.na_sequence_id
            AND gij.annotated_intron = 'Yes'
            AND gij.org_abbrev = ':ORG_ABBREV'
            AND gs.org_abbrev = ':ORG_ABBREV'
          GROUP BY gs.organism
        )
        SELECT gs.na_sequence_id
               , gs.source_id
               , ot.*
               , ':PROJECT_ID' as project_id
               , ':ORG_ABBREV' as org_abbrev
               , current_timestamp as modification_date
        FROM :SCHEMA.genomicseqattributes gs
             , org_tot ot
        WHERE gs.organism = ot.organism
          AND gs.na_sequence_id in (SELECT DISTINCT ij.na_sequence_id FROM apidb.intronjunction ij, dots.nasequence s where ij.na_sequence_id = s.na_sequence_id and s.taxon_id = :TAXON_ID)
          AND gs.org_abbrev = ':ORG_ABBREV'
:DECLARE_PARTITION
  ;
