:CREATE_AND_POPULATE
        SELECT DISTINCT substr(id, 1, 60) as id, substr(sequence, 1, 60) AS sequence,
	':PROJECT_ID' as project_id, :ORG_ABBREV as org_abbrev, CURRENT_TIMESTAMP as modification_date
        FROM (
          SELECT ns.source_id as id, ns.source_id as sequence
          FROM dots.NaSequence ns, sres.OntologyTerm oterm
          WHERE ns.sequence_ontology_id = oterm.ontology_term_id
            AND ns.taxon_id = :TAXON_ID
            AND oterm.name in ('random_sequence', 'contig', 'supercontig', 'chromosome','mitochondrial_chromosome','plastid_sequence','cloned_genomic','apicoplast_chromosome','maxicircle','kinetoplast')
          UNION
          SELECT dr.primary_identifier AS id, ns.source_id AS sequence
          FROM dots.NaSequence ns, dots.DbRefNaSequence drnf,
               sres.DbRef dr, sres.ExternalDatabaseRelease edr,
               sres.ExternalDatabase ed
          WHERE dr.primary_identifier IS NOT NULL
            AND ns.taxon_id = :TAXON_ID
            AND ns.na_sequence_id = drnf.na_sequence_id
            AND drnf.db_ref_id = dr.db_ref_id
            AND dr.external_database_release_id
                  = edr.external_database_release_id
            AND edr.external_database_id = ed.external_database_id
        ) subquery1
:DECLARE_PARTITION;

