:CREATE_AND_POPULATE
        SELECT ':PROJECT_ID' as project_id,
               :ORG_ABBREV as org_abbrev,
               current_timestamp as modification_date,
               sa.source_id,
               ns.sequence
        FROM :SCHEMA.GenomicSeqAttributes sa, dots.NaSequence ns
        WHERE sa.na_sequence_id = ns.na_sequence_id
          and sa.org_abbrev = :ORG_ABBREV
      
    
:DECLARE_PARTITION;

