DROP TABLE if exists :SCHEMA.:ORG_ABBREVGroupPhylogeneticProfileTmp;
/*

ATTENTION: This table is empty. We will populate it in the comparative graph
We are creating the partition here
*/

CREATE UNLOGGED TABLE :SCHEMA.:ORG_ABBREVGroupPhylogeneticProfileTmp (
    orthomcl_name   VARCHAR(16),
    profile_string text,
    project_id  varchar(20),
    org_abbrev  varchar(20),
    modification_date   timestamp
);

:CREATE_AND_POPULATE
SELECT ogt.* from :SCHEMA.:ORG_ABBREVGroupPhylogeneticProfileTmp ogt
:DECLARE_PARTITION;


DROP TABLE :SCHEMA.:ORG_ABBREVGroupPhylogeneticProfileTmp;
