:CREATE_AND_POPULATE

SELECT transcript_source_id, protein_source_id, gene_source_id, i.ncbi_tax_id, interpro_db_name, interpro_primary_id, 
       interpro_secondary_id, interpro_desc, interpro_start_min, interpro_end_min, interpro_e_value, interpro_family_id,
       ':ORG_ABBREV' as org_abbrev, current_timestamp as modification_date
 FROM apidb.interproresults i, sres.taxon t
 WHERE i.ncbi_tax_id = t.ncbi_tax_id
   AND t.taxon_id = :TAXON_ID;
    
:DECLARE_PARTITION;

