:CREATE_AND_POPULATE

        SELECT DISTINCT pn.pathway_node_id
          , tp.gene_source_id, tp.project_id, tp.org_abbrev, current_timestamp as modification_date,
        FROM :SCHEMA.transcriptpathway tp
          , sres.pathwaynode pn
        WHERE tp.pathway_id = pn.pathway_id
          AND tp.ec_number_gene like replace(pn.display_label, '-', '%')
	  and tp.org_abbrev = ':ORG_ABBREV'
      
    
:DECLARE_PARTITION;

