:CREATE_AND_POPULATE
        SELECT ':PROJECT_ID' as project_id,
            ':ORG_ABBREV' as org_abbrev,
            current_timestamp as modification_date,
            ta.source_id, eas.source_id AS pdb_chain,
               substr(eas.description, 1, 100) AS pdb_title,
               substr(eas.source_id
                      , 1
                      , length(eas.source_id) - (
                          CASE strpos(reverse(eas.source_id), '_')
                          WHEN 0 THEN length(eas.source_id)
                          ELSE strpos(reverse(eas.source_id), '_') END
                      )
               ) AS pdb_id,
               s.evalue_mant, s.evalue_exp,
               s.pident as percent_identity,
               ROUND((s.length / ta.protein_length) * 100) AS percent_plasmo_coverage,
               SUBSTR(tn.name, 1, 100) AS taxon,
               eas.taxon_id as pdb_taxon_id, ta.taxon_id as gene_taxon_id
        FROM apidb.PdbSimilarity s,
             apiDB.ProteinDataBank eas,
             sres.TaxonName tn,
             :SCHEMA.TranscriptAttributes ta
        WHERE ta.aa_sequence_id  = s.aa_sequence_id  
          AND s.pident = eas.protein_data_bank_id
          and tn.name_class = 'scientific name'
          AND eas.taxon_id = tn.taxon_id
          and ta.org_abbrev = ':ORG_ABBREV'
        ORDER BY ta.source_id, eas.source_id
      
    
:DECLARE_PARTITION;

