:CREATE_AND_POPULATE
    SELECT DISTINCT ':PROJECT_ID' as project_id
        , ':ORG_ABBREV' as org_abbrev
        , pbg.sequence_source_id
        , pbg.start_location
        , pbg.end_location
        , pbg.algorithm
        , pbg.value
      	, pbg.external_db_release_id
        , pbg.modification_date
    FROM apidb.proteinbedgraph pbg,
         dots.aasequence aas,
         apidb.organism org
    WHERE pbg.sequence_source_id = aas.source_id
        AND aas.taxon_id = org.taxon_id
        AND org.abbrev = ':ORG_ABBREV'
;
:DECLARE_PARTITION;


