:CREATE_AND_POPULATE
          SELECT
              ':PROJECT_ID' as project_id
              , :ORG_ABBREV as org_abbrev
              , current_timestamp as modification_date
              , gf.source_id gene_source_id
              , t.source_id transcript_source_id
              , taf.na_feature_id
              , spf.aa_feature_id
              , spf.aa_sequence_id
              , spf.parent_id
              , aal.start_min
              , aal.end_max
              , spf.algorithm_name
              , substr(s.sequence, aal.end_max::INTEGER, 1) peptide_sequence
          FROM
             dots.SignalPeptideFeature spf
            , dots.AaLocation aal
            , dots.TranslatedAaFeature taf
            , dots.TranslatedAaSequence tas
            , dots.GeneFeature gf
            , dots.AaSequence s
            , dots.Transcript t
          WHERE
              spf.aa_sequence_id = s.aa_sequence_id
              AND aal.aa_feature_id = spf.aa_feature_id
              AND t.na_feature_id = taf.na_feature_id
              AND taf.aa_sequence_id = tas.aa_sequence_id
              AND tas.aa_sequence_id = spf.aa_sequence_id
              AND gf.na_feature_id = t.parent_id
              AND tas.taxon_id = :TAXON_ID
              AND (spf.signal_probability >= .5
                  OR spf.signal_probability IS NULL
                  OR ((spf.means_score + spf.maxy_score) / 2) >= .5
                      OR ( spf.maxy_conclusion + spf.maxc_conclusion + spf.maxs_conclusion + spf.means_conclusion ) >= 3
                  )
          ORDER BY
              spf.aa_sequence_id, spf.aa_feature_id
        
    
:DECLARE_PARTITION;

