:CREATE_AND_POPULATE
        SELECT ':PROJECT_ID' as project_id
            , ':ORG_ABBREV' as org_abbrev
            , current_timestamp as modification_date
            , ta.source_id as transcript_source_id
            , ta.gene_source_id AS gene_source_id
            , tmf.topology AS tmf_topology
            , aal.start_min AS tmf_start_min
            , aal.end_max AS tmf_end_max
            , substr(tas.sequence, aal.end_max::INTEGER - aal.start_min::INTEGER + 1, aal.start_min::INTEGER) AS tmf_sequence
            , tmf.aa_feature_id tmf_aa_feature_id
            , tmf.aa_sequence_id tmf_aa_sequence_id
            , tas.source_id as protein_source_id
        FROM dots.aalocation aal
          , :SCHEMA.transcriptattributes ta
          , dots.translatedaafeature taf
          , dots.translatedaasequence tas
          , dots.transmembraneaafeature tmf
        WHERE ta.na_feature_id = taf.na_feature_id
        AND taf.aa_sequence_id = tas.aa_sequence_id
        AND tas.aa_sequence_id = tmf.aa_sequence_id
        and tmf.aa_feature_id = aal.aa_feature_id
        and ta.org_abbrev = ':ORG_ABBREV'
    
:DECLARE_PARTITION;

