#!/usr/bin/perl
use strict;

my %h;
while (<STDIN>) {
  next unless /^tables: '(.+)'/;
  my @a = split(/, /, $1);
  foreach my $t (@a) {
    $h{$t} = 1;
  }
}
foreach my $t (sort keys %h) {
  next if $t =~/apidbtuning/;
  print STDOUT "$t\n";
}

