
      
        create table DomainAssignment  as
        select sa.full_id, sa.group_name,
               r.interpro_primary_id as accession,
               r.interpro_desc as description,
               CAST (NULL as NUMERIC) as domain_index,
               sa.aa_sequence_id,
               r.interpro_start_min as start_min,
               r.interpro_end_min as end_max
        from SequenceAttributes sa,  apidb.interproresults r
        where sa.full_id = r.protein_source_id
          and upper(r.interpro_db_name) = 'PFAM'
      
    ;


      
        create index domain_accession_ix 
               on DomainAssignment  (accession, full_id, group_name)
      
    ;


      
        create table domainIndex as
        select row_number() OVER () as domain_index, accession
        from (select distinct accession
              from DomainAssignment 
              order by accession)
      
    ;


      
        create index domainIdxIdx on DomainIndex(accession, domain_index)
      
    ;


      
        update DomainAssignment  da
        set domain_index = (select domain_index
                            from DomainIndex
                            where accession = da.accession)
      
    ;


      
        create index domain_ix_ix 
               on DomainAssignment  (domain_index, accession, full_id)
      
    ;


      
        create index domain_group_ix 
               on DomainAssignment  (group_name, accession, full_id)
      
    ;


      
        create index domain_seq_ix 
               on DomainAssignment  (aa_sequence_id, accession, full_id, group_name)
      
    ;

