:CREATE_AND_POPULATE

      
        CREATE TABLE CodingSequence  AS
        SELECT ta.source_id, ta.project_id,
               SUBSTR(sns.sequence, tf.translation_start::INTEGER,
                      tf.translation_stop::INTEGER - tf.translation_start::INTEGER + 1) as sequence
        FROM TranscriptAttributes ta, dots.SplicedNaSequence sns, dots.TranslatedAaFeature tf
        WHERE ta.source_id = sns.source_id
         AND ta.na_feature_id = tf.na_feature_id
      
    
:DECLARE_PARTITION;

