
      
        create index EstSumm_libOverlap_ix 
                     ON EstAlignmentGeneSummary 
                        (library_id, percent_identity, is_consistent,
                         est_gene_overlap_length, percent_est_bases_aligned)

      
    ;


      
        create index EstSumm_estSite_ix 
                     ON EstAlignmentGeneSummary 
                        (target_sequence_source_id, target_start, target_end,
                         library_id)

      
    ;

