
      
        create index gijnew_loc_ix  on GeneIntronJunction  (na_sequence_id,segment_start,segment_end,is_reversed)
      
    ;


      
        create index gijnew_gnscid_ix  on GeneIntronJunction  (intron_feature_id)
      
    ;


      
        create index gijnew_txnloc_ix 
         on GeneIntronJunction 
            (taxon_id, na_sequence_id, segment_start, segment_end, is_reversed,
             total_unique, total_isrpm, annotated_intron)
      
    ;

