        create gijnew_loc_ix  on :SCHEMA.GeneIntronJunction  (na_sequence_id,segment_start,segment_end,is_reversed)
    ;
     
        create gijnew_gnscid_ix  on :SCHEMA.GeneIntronJunction  (intron_feature_id)
    ;

        create gijnew_txnloc_ix 
         on :SCHEMA.GeneIntronJunction 
            (taxon_id, na_sequence_id, segment_start, segment_end, is_reversed,
             total_unique, total_isrpm, annotated_intron)
      
    ;

