        CREATE INDEX :SCHEMA.GeneId_gene_idx  ON :SCHEMA.GeneId  (gene, id)
    ;

        CREATE INDEX :SCHEMA.GeneId_id_idx  ON :SCHEMA.GeneId  (id, gene)
    ;

        CREATE INDEX :SCHEMA.GeneId_uniqid_idx  ON :SCHEMA.GeneId  (unique_mapping, id, gene)
    ;

        CREATE INDEX :SCHEMA.GeneId_lowid_idx  ON :SCHEMA.GeneId  (lower(id), gene)
    ;

        CREATE INDEX :SCHEMA.GeneId_uniqlowid_idx  ON :SCHEMA.GeneId  (unique_mapping, lower(id), gene)
    ;

