
      
        CREATE INDEX GeneId_gene_idx  ON :ORG_ABBREVGeneId  (gene, id)

      
    ;


      
        CREATE INDEX GeneId_id_idx  ON :ORG_ABBREVGeneId  (id, gene)

      
    ;


      
        CREATE INDEX GeneId_uniqid_idx  ON :ORG_ABBREVGeneId  (unique_mapping, id, gene)

      
    ;


      
        CREATE INDEX GeneId_lowid_idx  ON :ORG_ABBREVGeneId  (lower(id), gene)

      
    ;


      
        CREATE INDEX GeneId_uniqlowid_idx  ON :ORG_ABBREVGeneId  (unique_mapping, lower(id), gene)

      
    ;

