:CREATE_AND_POPULATE

      
        CREATE TABLE GenomicSequenceSequence  AS
        SELECT sa.source_id, cast(apidb.project_id(tn.name) as varchar(20)) as project_id,
               ns.sequence
        FROM GenomicSeqAttributes sa, dots.NaSequence ns, sres.TaxonName tn
        WHERE sa.na_sequence_id = ns.na_sequence_id
          AND ns.taxon_id = tn.taxon_id
          AND tn.name_class = 'scientific name'
      
    
:DECLARE_PARTITION;

