        create unique index :SCHEMA.:ORG_ABBREVpk_SeqAttr_  ON :SCHEMA.:ORG_ABBREVGenomicSeqAttributes  (lower(source_id), project_id)
    ;

        create unique index :SCHEMA.:ORG_ABBREVSeqAttr_source_id  ON :SCHEMA.:ORG_ABBREVGenomicSeqAttributes  (source_id)
    ;

        create unique index :SCHEMA.:ORG_ABBREVSeqAttr_naseqid  ON :SCHEMA.:ORG_ABBREVGenomicSeqAttributes  (na_sequence_id)
    ;

        create unique index :SCHEMA.:ORG_ABBREVSeqAttr_taxsrc_id  ON :SCHEMA.:ORG_ABBREVGenomicSeqAttributes  (taxon_id, source_id)
    ;
