        create unique index :SCHEMA.pk_SeqAttr_  ON :SCHEMA.GenomicSeqAttributes  (lower(source_id), project_id)
    ;

        create unique index :SCHEMA.SeqAttr_source_id  ON :SCHEMA.GenomicSeqAttributes  (source_id)
    ;

        create unique index :SCHEMA.SeqAttr_naseqid  ON :SCHEMA.GenomicSeqAttributes  (na_sequence_id)
    ;

        create unique index :SCHEMA.SeqAttr_taxsrc_id  ON :SCHEMA.GenomicSeqAttributes  (taxon_id, source_id)
    ;
