        create index :SCHEMA.:ORG_ABBREVexprof_idx 
          on :SCHEMA.:ORG_ABBREVProfile  (source_id, profile_type, profile_set_name)
    ;

        create index :SCHEMA.:ORG_ABBREVprofset_idx 
          on :SCHEMA.:ORG_ABBREVProfile  (profile_set_name, profile_type)
    ;

        create index :SCHEMA.:ORG_ABBREVsrcdset_idx 
          on :SCHEMA.:ORG_ABBREVProfile  (source_id, dataset_subtype, dataset_type)
    ;

