:CREATE_AND_POPULATE
        WITH pAttr AS (
           SELECT distinct source_id, aa_sequence_id
           FROM ProteinAttributes where org_abbrev = ':ORG_ABBREV')
        SELECT pa.source_id, tas.sequence,
        :PROJECT_ID as project_id, :ORG_ABBREV as org_abbrev, current_timestamp as modification_date
        FROM pAttr pa, dots.TranslatedAaSequence tas
        WHERE pa.aa_sequence_id = tas.aa_sequence_id
:DECLARE_PARTITION;
