:CREATE_AND_POPULATE

      
        CREATE TABLE ProteinSequence  AS
        WITH pAttr AS (
           SELECT distinct source_id, aa_sequence_id
           FROM ProteinAttributes)
        SELECT pa.source_id, pi.name AS project_id, tas.sequence
        FROM pAttr pa, dots.TranslatedAaSequence tas, core.Projectinfo pi
        WHERE pa.aa_sequence_id = tas.aa_sequence_id
          AND pi.project_id = tas.row_project_id
      
    
:DECLARE_PARTITION;

