:CREATE_AND_POPULATE

      
        create table RnaSeqStats  as
        select study_id, study_name, dataset_name, taxon_id, round(avg(num_reads::integer),0) as avg_unique_reads
        from (select sl.node_set_id as study_id
                , s.name || '[' || s.node_type || ']' as study_name
                , ed.name as dataset_name
                , ds.taxon_id
                , c.value as num_reads
            from apidb.Datasource ds
                , sres.ExternalDatabase ed
                , sres.ExternalDatabaseRelease edr
                , study.nodeSet s, study.nodeNodeSet sl
                , study.ProtocolAppNode pan
                , study.Characteristic c
                , sres.OntologyTerm ot
            where ds.external_database_name = ed.name
                and ed.external_database_id = edr.external_database_id
                and edr.external_database_release_id = s.external_database_release_id
                and sl.node_set_id = s.node_set_id
                and sl.protocol_app_node_id = pan.protocol_app_node_id
                and pan.protocol_app_node_id = c.protocol_app_node_id
                and c.qualifier_id = ot.ontology_term_id
                and (ot.source_id = 'EUPATH_0000460' or ot.source_id = 'EuPathUserDefined_00507')
        ) subquery1
        group by study_id, study_name, dataset_name, taxon_id
        union
        select study_id, study_name, dataset_name, taxon_id, round(2*avg(num_reads::integer),0) as avg_unique_reads
        from (select sl.node_set_id as study_id
                , s.name || '[' || s.node_type || ']' as study_name
                , ed.name as dataset_name
                , ds.taxon_id
                , c.value as num_reads
            from apidb.Datasource ds
                , sres.ExternalDatabase ed
                , sres.ExternalDatabaseRelease edr
                , study.nodeSet s, study.nodeNodeSet sl
                , study.ProtocolAppNode pan
                , study.Characteristic c
                , sres.OntologyTerm ot
            where ds.external_database_name = ed.name
                and ed.external_database_id = edr.external_database_id
                and edr.external_database_release_id = s.external_database_release_id
                and sl.node_set_id = s.node_set_id
                and sl.protocol_app_node_id = pan.protocol_app_node_id
                and pan.protocol_app_node_id = c.protocol_app_node_id
                and c.qualifier_id = ot.ontology_term_id
                and (ot.source_id = 'EUPATH_0000468' or ot.source_id = 'EuPathUserDefined_00515' or ot.source_id = 'EUPATH_0000476' or ot.source_id = 'EuPathUserDefined_00523')
        ) subquery2
        group by study_id, study_name, dataset_name, taxon_id
      
    
:DECLARE_PARTITION;

