:CREATE_AND_POPULATE
        SELECT  sa.project_id
	     , sa.org_abbrev
	     , current_timestamp as modification_date
	     , sa.full_id
             , sa.group_name
             -- , sec.uniprot_accession
             , ec.ec_number
             , ec.description
             , ec.parent_id as ec_parent
             , ec.ec_number_1
             , ec.ec_number_2
             , ec.ec_number_3
             , ec.ec_number_4
        FROM :SCHEMA.sequenceattributes sa
           , dots.AASequence aa
           , dots.AASequenceEnzymeClass sec
           , sres.ENZYMECLASS ec
        WHERE sa.aa_sequence_id = aa.aa_sequence_id
        AND sec.aa_sequence_id  = aa.aa_sequence_id
        AND sec.enzyme_class_id = ec.enzyme_class_id
	AND sa.org_abbrev = ':ORG_ABBREV'
:DECLARE_PARTITION
;

