
      
CREATE TABLE TypeAheadCounts  AS
   (SELECT DISTINCT dr.primary_identifier as option_id,
                   count(distinct aaf.aa_sequence_id) AS protein_count
   FROM dots.DbRefAaFeature draf, sres.DbRef dr, dots.aafeature aaf,
        sres.ExternalDatabaseRelease edr, sres.ExternalDatabase ed
   WHERE draf.db_ref_id = dr.db_ref_id
   AND dr.external_database_release_id
       = edr.external_database_release_id
   AND edr.external_database_id = ed.external_database_id
   AND aaf.aa_feature_id = draf.aa_feature_id
   GROUP BY dr.primary_identifier
   )
   UNION
   (SELECT DISTINCT ec.ec_number AS option_id,
          COUNT(DISTINCT asec.aa_sequence_id) AS protein_count
   FROM sres.enzymeClass ec,
        dots.aaSequenceEnzymeClass asec
   WHERE  asec.enzyme_class_id = ec.enzyme_class_id
   GROUP BY ec.ec_number)
   UNION                
   (SELECT DISTINCT gt.source_id AS option_id,
           COUNT(DISTINCT aaf.aa_sequence_id) AS protein_count
    FROM dots.AaFeature aaf,
         dots.GoAssociation ga, sres.OntologyTerm gt,
         dots.GoAssociationInstance gai,core.TableInfo ti
    WHERE aaf.aa_sequence_id = ga.row_id
    AND ga.table_id = ti.table_id
    AND ti.name = 'ExternalAASequence'
    AND ga.go_term_id = gt.ontology_term_id
    AND ga.go_association_id = gai.go_association_id
    GROUP BY gt.source_id)
      
    ;


      
CREATE INDEX TypeAheadCounts_idx  ON TypeAheadCounts  (option_id)
      
    ;

