
      
      CREATE TABLE SequenceEnzymeClass  AS (
        SELECT sa.full_id
             , sa.group_name
             -- , sec.uniprot_accession
             , ec.ec_number
             , ec.description
             , ec.parent_id as ec_parent
             , ec.ec_number_1
             , ec.ec_number_2
             , ec.ec_number_3
             , ec.ec_number_4
        FROM sequenceattributes sa
           , dots.AASequence aa
           , dots.AASequenceEnzymeClass sec
           , sres.ENZYMECLASS ec
        WHERE sa.aa_sequence_id = aa.aa_sequence_id
        AND sec.aa_sequence_id  = aa.aa_sequence_id
        AND sec.enzyme_class_id = ec.enzyme_class_id
      )
      
    ;


      
        CREATE INDEX SequenceEnzymeClass_idx1  ON SequenceEnzymeClass  (group_name, ec_number, description)
      
    ;


      
        CREATE INDEX SequenceEnzymeClass_idx2  ON SequenceEnzymeClass  (full_id, ec_number, description)
      
    ;

