        CREATE TABLE :SCHEMA.CompoundTypeAheads  AS
        SELECT ca.source_id AS compound_id,
              ca.source_id  || ' (' || ca.compound_name || ')' AS display
        FROM  :SCHEMA.CompoundAttributes ca, :SCHEMA.PathwayCompounds pc
        WHERE  pc.chebi_accession = ca.source_id
        UNION
        SELECT ca.source_id AS compound_id,
              pc.compound_source_id || ' (' || ca.compound_name || ')' AS display
        FROM  :SCHEMA.CompoundAttributes ca, :SCHEMA.PathwayCompounds pc
        WHERE  pc.chebi_accession = ca.source_id
    ;

